cmake-next/Modules/ExternalProject.cmake

At the moment ExternalProject is initializing all the submodules of a git repository,
even if the user only wants to checkout a subset of submodules . This patch initialize only
the selected submodules, reducing the waiting time for repository with many submodules 
(such as https://github.com/boostorg/boost ).
What is the policy for ExternalProject patches? YCM accept them or they should be submitted upstream?

[ExternalProject] init only selected git submodule

---

modules/YCMEPHelper.cmake

<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' height=40></a>
<a href='https://www.codereviewhub.com/robotology/ycm/pull/92?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/ycm/pull/92'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a href='#crh-end'></a>

[YCMEPHelper] Fix passing explicit *_COMMAND

---

modules/YCMEPHelper.cmake
tools/YCMBootstrap.cmake

This caused the issue described in https://gitlab.kitware.com/cmake/cmake/issues/16407 .

YCMBootstrap: Avoid truncating env variables list to first element in Windows

---

3rdparty/CMakeLists.txt

Fix https://github.com/robotology/ycm/issues/103
@drdanz Do you want to fix this also for v0.1.* releases ?

Fix OVITO git repository URL

---

help/release/0.2.3.rst
modules/InstallBasicPackageFiles.cmake

There was an error in `InstallBasicPackageFiles.cmake` file which was forcing the user to set in its project cmake file specific GLOBAL variable for properly export the project.
In particular, under specific circumstances, `set_and_check(${_IBPF_VARS_PREFIX}_INCLUDEDIR \"@PACKAGE_${_IBPF_VARS_PREFIX}_INCLUDEDIR@\")` was failing while importing a target using `find_package(<target_name>)`.
This behaviour is fixed [changing set_and_check() with set()](https://github.com/robotology/ycm/compare/master...claudiofantacci:fix/InstallBasicPackageFiles?expand=1#diff-9a0ae61cd4c59dc1be1469c2726733c7L281), thus preserving compatibility.
Furthermore, the file documentation has also been updated.

Fix InstallBasicPackageFiles preserving compatibility

---

modules/AddInstallRPATHSupport.cmake
modules/InstallBasicPackageFiles.cmake

This PR is only bout documentation, it does not add, nor remove, any functionality.
In particular:
- InstallBasicPackageFiles.cmake: I added and customized the documentation found in `CMakePackageConfigHelpers` relative to the following parameters: `VERSION`, `COMPATIBILITY`, `NO_SET_AND_CHECK_MACRO` and `NO_CHECK_REQUIRED_COMPONENTS_MACRO`. In this way the documentation is self contained in our module and does not require to jump here and there for understanding the meaning of the required parameters. A comment that links to the original CMake documentation has been left.
- AddInstallRPATHSupport.cmake: There was just a small typo.

Correct typos and add documentation of AddInstallRPATHSupport.cmake and InstallBasicPackageFiles.cmake

---

find-modules/FindOpenCV.cmake

It was an internal option of the FindOpenCV.cmake file, but it was not marked_as_advanced

[FindOpenCV] Cleanup LINK_LIB_HIGHGUI

---

modules/YCMEPHelper.cmake
tools/YCMBootstrap.cmake

This variable specifies an option version requested when searching for a system YCM package.
This solves https://github.com/robotology/robotology-superbuild/issues/21 .
Furthermore, add some documentation about the CMake variable read in input by this script.

Introduce YCM_MINIMUM_VERSION input in YCMBootrap

---

help/release/0.8.0.rst
modules/InstallBasicPackageFiles.cmake

This argument support dependencies that should be located only if the
targets are built STATIC (i.e. libraries linked as PRIVATE).

InstallBasicPackageFiles: Add PRIVATE_DEPENDENCIES argument

---

YCMConfig.cmake.in
cmake-next/CMakeLists.txt

Just a follow-up to #139 so that downstreams can actually use these modules. The only relevant value here is `3.11` per [cmake-next/CMakeLists.txt](https://github.com/robotology/ycm/blob/5503af083d2719f4bda1ddfe979ffad8ea3fd66b/cmake-next/CMakeLists.txt).

Add CMake 3.9+ stuff to module path on YCM load

---

help/release/0.9.1.rst
modules/FindOrBuildPackage.cmake

The typo is obvious. I came across this when configuring a project with `find_or_build_package(MyPackage CONFIG)`. The error message stated:
```
CMake Error at /usr/local/share/YCM/modules/FindOrBuildPackage.cmake:175 (find_package):
find_package given options exclusive to Module mode:
MODULE
and options exclusive to Config mode:
CONFIG
The options are incompatible.
Call Stack (most recent call first):
CMakeLists.txt:5 (find_or_build_package)
-- Configuring incomplete, errors occurred!
```
It originated at:
https://github.com/robotology/ycm/blob/4620eeead4f7f855cf2b0f1565a89f93e3e427c5/modules/FindOrBuildPackage.cmake#L172-L176
In fact, `_${_PKG}_CONFIG` is empty at this point, because `${ARGN}` was empty here:
https://github.com/robotology/ycm/blob/4620eeead4f7f855cf2b0f1565a89f93e3e427c5 …

Fix typo, actually compare first argument to known find_package options

---

find-modules/FindESDCANAPI.cmake
help/release/0.9.1.rst

This PR fixes the issue https://github.com/robotology/icub-main/issues/552 .

Fix compatibility of FindESDCANAPI.cmake with 64 bit libraries

---

cmake-next/proposed/ExternalProject-download.cmake.in
cmake-next/proposed/ExternalProject-verify.cmake.in
cmake-next/proposed/ExternalProject.cmake
help/release/0.10.0.rst
modules/IncludeUrl.cmake
modules/YCMEPHelper.cmake

Update `ExternalProject` from CMake `master` and apply the patch to avoid deleting the clones.
TODO: 
CC: @traversaro

ExternalProject sync

---

help/release/0.10.0.rst
modules/YCMEPHelper.cmake

When creating a super-build, the variable CMAKE_TOOLCHAIN_FILE should be passed along to the subprojects. A more detailed discussion can be found on #129.
The implemented solution is the one proposed by @traversaro here https://github.com/robotology/ycm/issues/129#issuecomment-400388086, and was tested in the context of compiling gazebo for Windows using vcpkg.

Pass CMAKE_TOOLCHAIN_FILE variable to subprojects

---

find-modules/FindACE.cmake
help/release/0.10.0.rst

The new imported targets are
* `ACE::ACE` (links the ACE library)
* `ACE::ACE_INLINE` (INTERFACE library for ACE inlines only)
The `ACE::ACE` target passes `__ACE_INLINE__` by default, this can be
changed by setting `ACE_INLINE` = `OFF`.
Using the following variables is no longer necessary, and therefore
their usage is deprecated.
* `ACE_ADDR_HAS_LOOPBACK_METHOD`
* `ACE_COMPILES_WITHOUT_INLINE_RELEASE`
* `ACE_COMPILES_WITHOUT_INLINE_DEBUG`
Also cleanup and small refactor

FindACE: Add imported targets

---

find-modules/CMakeLists.txt
find-modules/Findassimp.cmake

This PR adds `Findassimp.cmake` in `find-module` folder, as described in #224.
The module defines the imported target `assimp::assimp` and define the folloiwng variables according to the upstream `assimp-config` files:
- `ASSIMP_FOUND`:  true if assimp has been found and can be used
- `ASSIMP_ROOT_DIR`: the root directory where the installation can be found
- `ASSIMP_INCLUDE_DIRS`: include directories for assimp
- `ASSIMP_LIBRARIES`: libraries to link against assimp
- `ASSIMP_LIBRARY_DIRS`: link directories
- `ASSIMP_VERSION`: assimp version
- `ASSIMP_VERSION_MAJOR`: ASSIMP major version
- `ASSIMP_VERSION_MINOR`: ASSIMP minor version
- `ASSIMP_VERSION_revision`: ASSIMP revision version
The `ASSIMP_VERBOSE` variable may be set to enable a detailed module log.
Closes #224.

Add Findassimp.cmake

---

help/release/0.10.0.rst
modules/YCMEPHelper.cmake

Fixes #18 
The `YCMEPHelper` module now adds subproject to the main install target, if they provide a `cmake_install.cmake` file in their build directory. This file is automatically provided by CMake for projects installing at least one file. This feature should be considered experimental and might be modified or removed in the future.
Please note that non-relocatable file will contain the path for the project installation (i.e. the path to the `install` folder inside the superbuild binary directory), not to `CMAKE_INSTALL_PREFIX`.

YCMEPHelper: Add subproject install to main build

---

find-modules/CMakeLists.txt
find-modules/FindGLM.cmake
find-modules/Findassimp.cmake

This PR adds the `FindGLM.cmake` find module to look for the [GLM](https://github.com/g-truc/glm) header-only library in the system.
The upstream GLM library sports a `gmlConfig.cmake` that imports a `glm` target. However some Linux distro are shipped with an old GLM version without any CMake config or find module. As a consequence, I propose to add `FindGLM.cmake` that first calls `find_package(GLM CONFIG QUIET)` trying to use the `gmlConfig.cmake`, if present. Otherwise it replicates the upstream behaviour providing the `glm` target and by parsing the library version.
**Bonus round 🌟**: fix a typo in `Findassimp.cmake` documentation 🙃

Add FindGLM.cmake

---

cmake-next/CMakeLists.txt
help/release/0.10.2.rst

FetchContent complains about a missing `.in` file [here](https://github.com/Kitware/CMake/blob/v3.11.4/Modules/FetchContent.cmake#L769-L775) ([declaration](https://github.com/Kitware/CMake/blob/v3.11.4/Modules/FetchContent.cmake#L490)). That would be [Modules/FetchContent/CMakeLists.cmake.in](https://github.com/Kitware/CMake/blob/v3.11.4/Modules/FetchContent/CMakeLists.cmake.in).

Download required FetchContent's template file

---

YCMConfig.cmake.in
cmake-next/CMakeLists.txt
help/release/0.10.2.rst

YCM 0.10 pulls *FindDoxygen.cmake* from CMake's 3.9 sources (https://github.com/robotology/ycm/commit/0c13699d2140eb1af9e91b18bef60f8445cb2b50). This module is not compatible with the latest Doxygen 1.8.15 release, see [bug report at GitLab](https://gitlab.kitware.com/cmake/cmake/issues/18738). This has been fixed in CMake 3.13.4: https://github.com/Kitware/CMake/commit/e81fd5d5ba24e46a3a27c6a4e061932cf2022ef2.
This patch imports *FindDoxygen.cmake* from v3.13.4. See [v3.9.6...v3.13.4 file diff](https://github.com/Kitware/CMake/compare/v3.9.6...v3.13.4#diff-482f93beb36206a6084ca91bb7bf60f8) ([bracket arguments](https://cmake.org/cmake/help/v3.5/manual/cmake-language.7.html#bracket-argument) are supported in CMake 3.5).

Import FindDoxygen from CMake 3.13.4, fix version checks

---

find-modules/Findassimp.cmake
help/release/0.10.3.rst

This PR fix `assimp_FOUND` missing definition in `Findassimp.cmake` by properly setting the package name in `find_package_handle_standard_args` calls.

Fix assimp_FOUND missing definition in Findassimp

---

modules/InstallBasicPackageFiles.cmake

The documentation for `install_basic_package_files()` claims:
> If no ``VERSION`` is given, the ``PROJECT_VERSION`` variable is used.
However, this was not yet implemented, which this pull request aims to fix.

`VERSION` now defaults to `PROJECT_VERSION` as advertised

---

modules/InstallBasicPackageFiles.cmake

This PR addresses several minor things in the docs and comments.
The remark on `PATH_VARS` and `INCLUDE_FILE|INCLUDE_CONTENT` in https://github.com/robotology/ycm/commit/b3a1289716222f0a3f369f6c4184df5c723a0497 documents something which might be a design problem. `install_basic_package_files()` uses `string(CONFIGURE)` to expand `@...@` variables in the included content and then stores the expanded content in a variable `INCLUDED_CONTENT` which is subsequently expanded into the config file by `configure_package_config_file()`. Because variable substitution in `configure_file()` is not recursive (as far as I can tell), this implies that included content doesn't have access to the `PATH_VARS` variables. To use these, it is necessary to provide a custom config file.

Minor documentation fixes/improvements

---

modules/InstallBasicPackageFiles.cmake

Originally reported in https://github.com/robotology/yarp/issues/2082 .

InstallBasicPackageFiles: fix missing bracket in include statement

---

find-modules/FindIPOPT.cmake

Instead, search for the IpOpt headers using the standard find_path CMake command. 
Fix https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports/issues/3 .

FindIPOPT: avoid hardcoding IPOPT_INCLUDE_DIRS to  ${IPOPT_DIR}/include/coin

---

find-modules/FindIPOPT.cmake

The use of NO_DEFAULT_PATH complicates finding the library using the standard enviroment variables such as CMAKE_PREFIX_PATH.

FindIPOPT: Remove use of NO_DEFAULT_PATH

---

help/manual/ycm-superbuild.7.rst
help/release/0.11.0.rst
modules/YCMEPHelper.cmake

The `YCM_EP_INSTALL_DIR` variable can be used to change where the subprojects will be installed (default `${PROJECT_BINARY_DIR}/install`).
You should not change the `YCM_EP_INSTALL_DIR` variable, unless you wish to build the superbuild only once, and discard the build directory.
In this case you should change this variable to the final destination of the build since, for many projects, the build is not relocatable.
Please also note that, if you change it to a folder that is not writable by current user, you will have to run the whole build as superuser.

YCMEPHelper: Introduce YCM_EP_INSTALL_DIR advanced variable

---

modules/YCMEPHelper.cmake

Fix https://github.com/robotology/ycm/issues/290 .  
This PR contains two fixes: 
* Add a missing semicolon `;` to the `${_YCM_EP_CMAKE_CACHE_DEFAULT_ARGS}` passed to the CMake invocation of the YCM boostrap: without that, the `-G<Generator>` command was considered as part of the last variable set in _YCM_EP_CMAKE_CACHE_DEFAULT_ARGS,  and effectively ignored. 
* The previous error for some reason was  preventing the use of `|` as list separtor in the `-DCMAKE_PREFIX_PATH:PATH=` argument of the CMake invocation to create problems, once fixed the CMake configuration was failing for this reason. As YCM bootstrap does not need to find anything using `CMAKE_PREFIX_PATH`, the easiest solution is just to remove it from the invocation command.

Fix issue 290 for which the default generator was always used by the bootstrapped YCM

---

find-modules/FindTinyXML.cmake

Unfortunately, vcpkg installs a really bad and custom `tinyxml-config.cmake` file (see https://github.com/robotology/robot-testing-framework/issues/107 and https://github.com/microsoft/vcpkg/pull/5544). As TinyXML has long been abandoned upstream, I think any CMake config we can find are something provided by packagers that have the high probability of breaking downstream user CMake logic, so I think the best option is just to disable searching for CMake config files at all for TinyXML.

Fix FindTinyXML.cmake script to work fine with vcpkg's installed tinyxml

---

3rdparty/eigen3.cmake

Apparently also the GitHub repo is going to be removed as the BitBucket one.
See https://github.com/eigenteam/eigen-git-mirror/commit/36b95962756c1fce8e29b1f8bc45967f30773c00 .
As the commit hash are different, I also changed the commit hash to point to the same commit.

Change eigen3.cmake to use GitLab repo

---

modules/InstallBasicPackageFiles.cmake

Unify default `INSTALL_DESTINATION` path

---

modules/InstallBasicPackageFiles.cmake

Unfortunately the code in my previous PR #269 ended up behaving inconsistently depending on the CMake version. Cf. https://github.com/robotology/ycm/issues/262#issuecomment-579840557 for an explanation.

Fix CMake version dependent inconsistency

---

find-modules/FindESDCANAPI.cmake

If the ESDCANAPI ntcan library is installed via a custom vcpkg port instead of the official installers, 
its location will not be already listed in the `ESDCAN_LIB_DIRS`, and instead  would be found with the usual `CMAKE_PREFIX_PATH` introspection. 
Note that the precedence will remain on the PATHS specified by `ESDCAN_LIB_DIRS`, so we do not risk to break any existing behavior with this change.

Remove NO_DEFAULT_PATH from ESDCANAPI find_library

---

find-modules/FindIPOPT.cmake

I  was using a recent CMake (3.17) on Windows, and for IPOPT_INCLUDE_DIRS the `FindIPOPT.cmake` script was finding the wrong path `C:/robotology/vcpkg/installed/x64-windows/include/coin` instead of the correct `C:/robotology/vcpkg/installed/x64-windows/include`. Note that all uses of IPOPT headers, even in their examples (see https://github.com/coin-or/Ipopt/blob/releases/3.13.1/examples/Cpp_example/MyNLP.hpp) use the direct inclusion of the headers (i.e. `#include <IpTNLP.hpp>`, not `#include <coin/IpTNLP.hpp>`. 
With this fix, the `FindIPOPT.cmake` should never find the wrong include path for IPOPT. To be honest, I do not know why it we never noticed this problem, it is possible that something subtle changed at the CMake level in CMake 3.17).

Fix find_path call to search for IPOPT_INCLUDE_DIRS

---

modules/YCMEPHelper.cmake

As YCM now requires CMake 3.12, this legacy logic can be removed.

YCMEPHelper: Cleanup logic to support CMake < 3.1

---

modules/FindOrBuildPackage.cmake

The workaround described in the documentation were removed in  https://github.com/robotology/ycm/commit/b8bdc35f7fe29ece91bd79427a42083268b150c3, but the relative documentation was still there.

Cleanup outdated documentation of  FindOrBuildPackage module

---

help/manual/ycm-superbuild.7.rst
help/release/0.12.0.rst
modules/YCMEPHelper.cmake

In some situations, it may be convenient to be able to specify some additional command line arguments that are passed during the cmake invocation of all CMake-based subprojects. 
This PR adds a `YCM_EP_ADDITIONAL_CMAKE_ARGS` CMake cache variable, that permits to specify some additional CMake arguments that are passed to all the subprojects of a superbuild.
This is similar to the `--cmake-args`  argument of catkin and colcon.

YCMEPHelper: Add YCM_EP_ADDITIONAL_CMAKE_ARGS

---

3rdparty/cmake-wiki/FindOctave.cmake

See the related discussions in: 
* https://github.com/robotology/idyntree/pull/677
* https://discourse.cmake.org/t/findoctave-cmake-in-cmake-community-wiki-broken-for-octave-5/1079
As the support for obtaining the `PREFIX` variable (that in CMake was stored as `OCTAVE_ROOT_DIR`) was removed in Octave upstream.
I think it is easier and less error prone (fail early, fail fast) to just remove support for the variable, so in the remote case that anyone relies on this variable, he will notice that automatically as soon as he updates his YCM version, instead of getting a failure when someone compiles his project with Octave 5.
This is also the reason why I propose this for the master branch and not for the `ycm-0.11` branch.
cc @lrapetti

Fix FindOctave.cmake for Octave 5

---

help/release/0.11.2.rst
modules/InstallBasicPackageFiles.cmake

Before the commit the PRIVATE_DEPENDENCIES argument of install_basic_package_files was ignored unless DEPENDENCIES was also set.

Fix handling of PRIVATE_DEPENDENCIES in install_basic_package_files

---

help/release/0.12.0.rst
modules/AddInstallRPATHSupport.cmake
tests/RunCMake/AddInstallRPATHSupport/AddInstallRPATHSupport_target_append_install_rpath.cmake
tests/RunCMake/AddInstallRPATHSupport/RunCMakeTest.cmake

* Added the new `target_append_install_rpath` to the `AddInstallRPATHSupport` module, to modify the rpath for a single target.

AddInstallRPATHSupport: Add target_append_install_rpath command

---

3rdparty/catch2.cmake
help/release/0.11.3.rst

Due to the recent release of CMake 3.18.0, which introduces a regression that breaks all YARP unit tests (see https://gitlab.kitware.com/cmake/cmake/-/issues/21017) we are forced to make an urgent and unplanned release of YCM to include the fixed version of the modules imported from Catch2.

3rd-party: Update Catch2 Git Repository to commit 229cc4823c8cbe67366da8179efc6089dd3893e9

---

3rdparty/catch2.cmake
help/release/0.11.4.rst

This fixes the issue with tests in CMake 3.18.1

3rd-party: Update Catch2 Git Repository to commit de3a208e167c6baee6e8dc46f2c0466b311324c2

---

find-modules/FindPortAudio.cmake

If a modern (unreleased but already available as 2020 in vcpkg) portaudio that installs CMake imported targets is available, use that in FindPortAudio .
Fix https://github.com/robotology/yarp/issues/2117 .

PortAudio: support for imported targets

---

find-modules/FindIPOPT.cmake
help/release/0.12.1.rst

This PR includes two changes:
* Take into account that header files are not installed in <prefix>/include/coin-or (see https://github.com/coin-or/Ipopt/blob/releases/3.13.0/ChangeLog)
* The ipopt on Windows binary provided by conda are compiled by MSVC and Flang, so they do not ship with all the ifortran related libraries. If this libraries are not found, do not add them in IPOPT_LIBRARIES to avoid a failure in `find_package_handle_standard_args` (see https://github.com/conda-forge/ipopt-feedstock/pull/47)

Fix FindIPOPT to work with IPOPT 3.13 and conda

---

find-modules/FindIPOPT.cmake

Apparently the default library names since IPOPT 3.13 changed, so let's try to keep aligned.
For an example of a name different from the usual one, see the Windows binaries available in the ipopt GitHub release page (see https://github.com/coin-or/Ipopt/releases/download/releases%2F3.13.3/Ipopt-3.13.3-win64-msvs2019-md.zip).
I found a reference  on the possible names in the IPOPT source code in https://github.com/coin-or/Ipopt/blob/releases/3.13.3/src/Interfaces/Ipopt.java#L167, so I used that one. For the debug names I tried to follow the old naming scheme, but to be honest that is just a guess. 
Related discussion: https://github.com/conda-forge/ipopt-feedstock/issues/53 .

FindIPOPT: Add more candidates for the library names on Windows

---

3rdparty/catch2.cmake
help/release/0.12.2.rst

The `ParseAndAddCatchTests.cmake` has several issues, and the module was deprecated upstream in favour of `Catch.cmake`
The new version fixes a few issues, but also prints a deprecation warning suggesting to switch to `Catch.cmake`

3rd-party: Update Catch2 Git Repository to tag v2.13.4

---

help/release/0.12.2.rst
modules/YCMEPHelper.cmake

I have noticed that upon enabling development mode on a superbuild subproject (either `YCM_EP_DEVEL_MODE_<project_name>` or `YCM_EP_MAINTAINER_MODE` set to `ON`, where `<project_name>` is orchestrated by YCM/ExternalProject), a specific target (e.g. `<project_name>-edit_cache`) is generated which opens the CMake cache editor, i.e. `ccmake`. It didn't work for me, though.
Then, I saw something like this in `build/CMakeFiles/<project_name>-edit_cache.dir/build.make` (real excerpt from generated Makefile by https://github.com/roboticslab-uc3m/asibot-main superbuild):
```make
external/ROBOTICSLAB_KINEMATICS_DYNAMICS/CMakeFiles/YCMStamp/ROBOTICSLAB_KINEMATICS_DYNAMICS-edit_cache: external/ROBOTICSLAB_KINEMATICS_DYNAMICS/CMakeFiles/YCMStamp/ROBOTICSLAB_KINEMATICS_DYNAMICS-configure …
```

Fix edit_cache targets in development mode

---

find-modules/Findassimp.cmake
help/release/0.12.2.rst

The logic of FindAssimp is broken on Windows, as on VS2019 it looks only for assimp libraries compiled under VS2019 (i.e. with the -vc150 suffix) but VS2019 is perfectly compatible with assimp libraries compiled with VS2015 or VS2017. This was causing the problem reported in https://github.com/robotology/idyntree/pull/832#issuecomment-779671792 .
The fix is to first look for an assimp CMake config file in the system, and only do the manual search if this is not found.

Fix FindAssimp on Windows

---

find-modules/Findassimp.cmake

Unfortunately what discussed in https://github.com/robotology/ycm/pull/371#issuecomment-780720827 turned out to be true. 
In particular, if I understood correctly (still needs to be confirmed) @randaz81 is having problem in https://github.com/robotology/cer due to the specific order of `find_package(YCM)`  and `find_package(gazebo)` calls (gazebo's CMake config file calls DART's CMake config file that calls `find_package(assimp)` , whose behavior change depending of weather `find_package(YCM)` was called or not). While this could be probably fixed by moving `find_package(gazebo)`  before `find_package(YCM)`, this PR should provide a more robust fix by having a logic to detect the malformed assimp configuration file of Ubuntu 20.04 and fixing it. 
cc @randaz81 if you could test this it …

Fix Findassimp.cmake in Ubuntu 20.04 and 18.04

---

3rdparty/CMakeLists.txt
3rdparty/ecm.cmake
docs/conf.py.in
help/release/0.13.0.rst

I'm not 100% sure that this is how we should handle this, since we could just add a dependency on ECM.
Anyway, ECM brings some extra build dependencies (Qt5, Python3), therefore for now I suggest to handle it in this way.
CC @triccyx

Import FindUDev.cmake from ECM repository

---

3rdparty/vtk.cmake
help/release/0.13.0.rst

The FindFFMPEG module now offers targets, but it requires to specify
the COMPONENTS to the find_package(FFMPEG) calls.
CC-Issue: robotology/yarp#2530
CC-Issue: robotology/yarp#2529

Update 'VTK Git Repository' to tag v9.0.1

---

.github/CODEOWNERS
.github/workflows/python.yml
tools/pip/README.md
tools/pip/pyproject.toml
tools/pip/setup.cfg
tools/pip/setup.py

Twin PR of https://github.com/robotology/yarp/pull/2573.
- Also the `ycm` package name [is already taken](https://pypi.org/project/ycm/) in PyPI. In this case, I can try to submit a PEP541 request in [pypa/pypi-support](https://github.com/pypa/pypi-support) to get the ownership. (done in https://github.com/pypa/pypi-support/issues/1096)
- For ycm the github workflow and wheel generation is much simpler since it does not contain any C++ code, and the wheel could be shared for all OSs.

 Package `ycm` with setuptools

---

3rdparty/cmrc.cmake
help/release/0.13.0.rst

The module is now able to produce `OBJECT` libraries
See also https://github.com/robotology/yarp/pull/2637

3rd party: Import the CMakeRC module from robotology-dependencies

---

3rdparty/cmrc.cmake
help/release/0.13.1.rst

Modules
=======
3rd Party
---------
* The :module:`CMakeRC` module is imported again from the official repository,
and it no longer prints the debug message.

3rdparty/cmrc: Retrieve latest version from original repository

---

3rdparty/qgv/FindGraphviz.cmake

When graphviz is not installed in system directories, its headers are installed in a path like:
~~~
<install_prefix>/include/graphviz/cgraph.h
~~~
Before this PR, even if `<install_prefix>` is added to the `CMAKE_PREFIX_PATH`, the snippet of code:
~~~cmake
find_path(Graphviz_INCLUDE_DIR
NAMES cgraph.h
PATHS ${Graphviz_POSSIBLE_INCDIRS}
/usr/include
/usr/include/graphviz
/usr/local/include
/usr/local/include/graphviz
HINTS ${Graphviz_PKG_INCLUDE_DIR})
~~~
would not find it, and would mark Graphviz as not found. In this PR, we add the `PATH_SUFFIXES` option so that regardless of the installation prefix Graphvix is correctly found. This for example would fix finding Graphviz when it is installed in a conda environment.
While this file is in `3rdparty/qgv`, I opened directly a PR here as the …

FindGraphviz: Fix finding graphviz not installed in system directories

---

.github/CODEOWNERS

As discussed on Teams, switch mantainer of YCM from @drdanz to @traversaro .

Switch main mantainer from drdanz to traversaro

---

docs/cmake.py

Following changes are done to build with new sphinx:
* Replaced htmlescape with html.escape
* Change import path for QtHelpBuilder and keep the older one as fallback
* Change number of return values in __call__ method
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=997429

Fix build with new sphinx

---

cmake-next/proposed/ExternalProject.cmake
cmake-next/proposed/RepositoryInfo.txt.in
help/release/0.13.1.rst
modules/YCMEPHelper.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/1074 .
CI is currently not working on this repo, so this branch will be tested in https://github.com/robotology/robotology-superbuild/pull/1075 .
We also release YCM 0.13.1 with this change, to ensure that we have a version compatible with CMake 3.23 .

ExternalProject: Check all possible locations of RepositoryInfo.txt.in file to avoid problem with CMake 3.23 and release YCM 0.13.1

---

CHANGELOG.md
help/release/0.13.2.rst

It may be necessary to quickly release patch releases of YCM if there are environment regression due to new CMake releases, see for example https://github.com/robotology/ycm/pull/393 . 
However, at the moment the release process is a bit cumbersome as it is necessary to modify and even create several files as part of the release process. To streamline this, I think it is convenient to switch to a single file CHANGELOG.md file.

Switch changelog format to single CHANGELOG.md in the root directory of the repo

---

.github/workflows/conda-forge-ci.yml

Thanks to conda-forge, we test against many CMake version. We just disable YCMBootstrap tests, as YCMBootstrap will soon be removed by a FetchContent-based solution (see https://github.com/robotology/ycm/issues/138).
Fix https://github.com/robotology/ycm/issues/114 .
Fix https://github.com/robotology/ycm/issues/366 .

Add CI with conda-forge-provided dependencies

---

CHANGELOG.md
modules/FindOrBuildPackage.cmake

In FindOrBuildPackage a preliminary `find_package` is run to decide if it make sense to provide to the 
user the `USE_SYSTEM_${_PKG}` option. However if `YCM_DISABLE_SYSTEM_PACKAGES`  is ON, the
`USE_SYSTEM_${_PKG}` option is already disabled, so we can skip the `find_package` calls.
This change should dramatically reduce the CMake configuration for superbuilds in which `YCM_DISABLE_SYSTEM_PACKAGES`  is ON and that have many subpackages.

 FindOrBuildPackage: Do not run find_package if YCM_DISABLE_SYSTEM_PACKAGES is ON

---

CHANGELOG.md
help/manual/ycm-superbuild-example.7.rst
help/manual/ycm-using.7.rst
modules/YCMEPHelper.cmake
tools/UseYCMFromSource.cmake
tools/YCMBootstrapFetch.cmake

Create `YCMBootstrapFetch.cmake` script to permit projects to bootstrap YCM by just using `FetchContent`.
A different file is created as the semantics of this new bootstrap script is a bit different, as it just make YCM available in the project, but it does not also adds it as a subproject in the superbuild sense. Superbuilds that want to switch from `YCMBootstrap.cmake` to `YCMBootstrapFetch.cmake` need to create `BuildYCM.cmake` script, and appropriately call `find_or_build_package(YCM)`, as done for example in the robotology-superbuild in https://github.com/robotology/robotology-superbuild/pull/1078 .
Fix https://github.com/robotology/ycm/issues/138 .

Create YCMBootstrapFetch to permit projects to bootstrap YCM using FetchContent

---

tools/YCMBootstrapFetch.cmake

This is useful to easily test YCM's forks when using `YCMBootstrapFetch`.

Support YCM_REPOSITORY in YCMBootstrapFetch

---

CHANGELOG.md
find-modules/CMakeLists.txt
find-modules/FinduSockets.cmake
find-modules/FinduWebSockets.cmake

Add CMake modules to find the [`uSockets`](https://github.com/uNetworking/uSockets) and [`uWebSockets`](https://github.com/uNetworking/uWebSockets) libraries.
They are supposed to be used as:
~~~cmake
find_package(uSockets REQUIRED)
target_link_libraries(<..> PRIVATE uSockets::uSockets)
~~~
and 
~~~cmake
find_package(uWebSockets REQUIRED)
target_link_libraries(<..> PRIVATE uWebSockets::uWebSockets)
~~~

Add FinduSockets.cmake and FinduWebSockets.cmake find-modules

---

.github/workflows/conda-forge-ci.yml

Currently the CI is failing on Linux and Windows with a weird conflict error. This is due to the fact that we are install mamba (from the conda-forge channel) on the top of miniconda3 (that by default install all the packages from the defaults channel). To make an analogy in apt world, this is like installing Debian, and then trying to install packages from the Ubuntu repo: something can go wrong.
To solve this problem, we install [mambaforge](https://github.com/conda-forge/miniforge) (a installer like miniconda3 but already using conda-forge packages) directly, so we always and only use packages from the conda-forge channel. 
Similar to:
* https://github.com/robotology/robotology-superbuild/pull/840
* https://github.com/robotology/robometry/pull/141
* …

Fix conda-ci GitHub Action CI by using mambaforge directly

---

CHANGELOG.md
find-modules/FindGLM.cmake

Fix https://github.com/ami-iit/yarp-device-openxrheadset/issues/35 and any possible related problem.
fyi @claudiofantacci @xEnVrE @S-Dafarra

FindGLM: define both glm and glm::glm imported targets

---

3rdparty/catch2.cmake
3rdparty/catch2/README.Catch2
3rdparty/cmrc.cmake
3rdparty/cmrc/CMakeRC.cmake
3rdparty/cmrc/README.CMakeRC
CHANGELOG.md

Furthermore, update some catch2 hashes that are not correct.
Fix https://github.com/robotology/ycm/issues/435 .

 Update vendored CMakeRC to latest commit 

---

CHANGELOG.md
find-modules/FindGLFW3.cmake

The idea is to mitigate the problems related to https://github.com/robotology/robotology-superbuild/pull/1598#issuecomment-1942172913, and mark the module as deprecated so that we can remove it in a future version of YCM. After this change, `find_package(GLFW3)` will set to true `glfw3_FOUND`, and will print a deprecation warning.
Note that glfw3Config.cmake is available since Ubuntu 20.04 : https://packages.ubuntu.com/focal/amd64/libglfw3-dev/filelist .

FindGLFW3: Use glfw3Config.cmake and mark module as deprecated

---

CHANGELOG.md
modules/YCMEPHelper.cmake

Fix part of https://github.com/robotology/robotology-superbuild/issues/1596 . As discussed in https://github.com/robotology/robotology-superbuild/issues/1596 one could use the `CMAKE_EXPORT_COMPILE_COMMANDS` environment variable, but this has the downside that is considered only if the build is created from zero, and it has no effects on existing builds.

YCMEPHelper: If CMAKE_EXPORT_COMPILE_COMMANDS is defined and ON, pass it to all subprojects

---

find-modules/FindOpenCV.cmake

`OpenCV_CONFIG` is not a variable set, so I have no idea why this was working without giving an error:
~~~
Could NOT find OpenCV (missing: OpenCV_CONFIG)
~~~
as it is happening in https://github.com/icub-tech-iit/ergocub-software/issues/248 .

FindOpenCV: Fix arguments passed to find_package_handle_standard_args

---

tests/RunCMake/cmake-next/RunCMakeTest.cmake
tests/RunCMake/cmake-next/find_package_Matlab.cmake

Fix https://github.com/robotology/ycm-cmake-modules/issues/450 .

Remove FindMatlab tests as FindMatlab is not part of ycm

---

modules/YCMEPHelper.cmake

Fix https://github.com/robotology/robotology-superbuild/issues/1700 . To be honest, I have no idea how this ever worked, or how it was working for users that reported that it was working fine for them (@LoreMoretti). However, if we want that executing a target always re-compile the project, indeed the ExternalProject's BUILD_ALWAYS option is explicitly designed for that:
> BUILD_ALWAYS <bool>
>
>    Enabling this option forces the build step to always be run. This can be the easiest way to robustly ensure that the external project's own build dependencies are evaluated rather than relying on the default success timestamp-based method. This option is not normally needed unless developers are expected to modify something the external project's build depends on in a way that is not …

YCMEPHelper: Set ExternalProject's BUILD_ALWAYS to ON to restore behaviour of old vendored YCM's ExternalProject

---

CMakeLists.txt
YCMConfig.cmake.in
internal-modules/YCMVersion.cmake
tools/YCMBootstrapFetch.cmake

* Permit to use FetchContent_MakeAvailable when YCM is used via FetchContent
* Switch `YCMBootstrapFetch` to use `FetchContent_MakeAvailable`, to avoid warning related to CMP0169 (fix https://github.com/robotology/ycm-cmake-modules/issues/453)
* Switch to define version variables in the standard CMake way, by passing VERSION to the `project` call. To do this, now `YCM_VERSION` is just major.minor.version, while the full version if required is provided in `YCM_VERSION_FULL`.
* Bump version to 0.17.0
* Deprecate `YCM_VERSION_REVISION`, `YCM_VERSION_DATE`, `YCM_VERSION_DATE_REVISION`, `YCM_VERSION_API`, `YCM_VERSION_SHORT`, `YCM_VERSION_SOURCE` and `YCM_VERSION_DIRTY`. This variable may be remove from YCM 0.18.0 .

Permit to use FetchContent_MakeAvailable when YCM is used via FetchContent and other related changes

---

.github/workflows/conda-forge-ci.yml
CMakeLists.txt

The support added in https://github.com/robotology/ycm-cmake-modules/pull/463 for consuming `YCM` via `FetchContent_MakeAvailable` had a bug, as `FetchContent_MakeAvailable` uses `add_subdirectory` under the hood to include a project, and `add_subdirectory` creates a new variable scope, so all variables set in it where not propagated to the context where  `FetchContent_MakeAvailable`. 
This PR fixes the issue by setting the used variable in the `PARENT_SCOPE`.

Fix support for consuming YCM via FetchContent_MakeAvailable and bump version to 0.17.1

---

.github/workflows/conda-forge-ci.yml
modules/CMakeLists.txt

The `ycm_ep_helper` used the two files `RepositoryInfo.txt.in` and `gitsafeclone.txt.in`, that however were not installed, so since YCM 0.16.7 and until YCM 0.18.0, `ycm_ep_helper`  worked fine (with CMake >= 3.22) only if YCM was bootstrapped or used via `FetchContent`, not if YCM was found via `find_package(YCM)`.

Fix calling ycm_ep_helper when YCM is consumed via find_package(YCM) and add test

---

modules/YCMEPHelper.cmake

Fix https://github.com/robotology/ycm-cmake-modules/issues/455 .

YCMEPHelper: Remove check for git global name and email being set even if NON_INTERACTIVE_BUILD is OFF

---

modules/YCMEPHelper/gitsafeclone.txt.in

CMake started complaining for projects that requested 3.5 as cmake_minimum_required (see https://gitlab.kitware.com/cmake/cmake/-/commit/55778f5a16ffe1b67123a31f6b568f2f7c0a1f36), so it make sense to bump the `cmake_minimum_required` used in `gitsafeclone` to 3.16 (as the general one of YCM).
This will fix all the warnings:
~~~
CMake Deprecation Warning at /home/runner/work/robotology-superbuild/robotology-superbuild/b/src/OsqpEigen/CMakeFiles/YCMTmp/OsqpEigen-gitsafeclone.cmake:8 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier. …

Fix "Compatibility with CMake < 3.10 will be removed" warnings in gitsafeclone.txt.in
