find-modules/FindIPOPT.cmake
Ref: https://github.com/robotology/icub-main/pull/344/commits/d51f5ebeae3be7450933329eae447fe1597455f7
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/drdanz%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/ycm/pull/91%23issuecomment-220545261%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-20T08%3A23%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20C …
=> Synch FindIPOPT.cmake with icub-main

modules/YCMEPHelper.cmake
Fix https://github.com/robotology/ycm/issues/108
=> Fix YCMBootstrap

YCMConfig.cmake.in
Fix https://github.com/robotology/robotology-superbuild/issues/22 .
=> Add 3.8 to cmake-next loop in YCMConfig.cmake.in

modules/AddInstallRPATHSupport.cmake
Closes #151
cc @francesco-romano
=> Update AddInstallRPATHSupport.cmake documentation

find-modules/FindGLFW3.cmake, help/release/0.9.1.rst
Fix https://github.com/robotology/ycm/issues/133
=> FindGLFW3: Fix https://github.com/robotology/ycm/issues/133

find-modules/FindPortAudio.cmake, help/release/0.9.2.rst
Also some other small improvements
=> FindPortAudio: Improve detection on VCPKG

help/release/0.10.0.rst, modules/YCMEPHelper.cmake
Fixes: #210 
@PeterBowman can you please test it and let me know if this works for you?
=> YCMEPHelper: Deprecate CONFIGURE_SOURCE_DIR in favour of SOURCE_SUBDIR

YCMConfig.cmake.in, help/manual/ycm-faq.7.rst, help/manual/ycm-superbuild-example.7.rst, help/manual/ycm-superbuild.7.rst, help/manual/ycm-using.7.rst, help/manual/ycm-variables.7.rst, help/release/0.10.0.rst, help/variable/YCM_USE_CMAKE.rst, help/variable/YCM_USE_CMAKE_NEXT.rst, help/variable/YCM_USE_CMAKE_VERSION.rst
=> Do not cache the 'YCM_USE_' variables

cmake-next/proposed/ExternalProject.cmake, modules/YCMEPHelper.cmake
There was a conflict with https://gitlab.kitware.com/cmake/cmake/commit/00b5f1a1b5f44167184e5602385986172afa7a3a
=> ExternalProject refresh

help/release/0.10.0.rst, modules/IncludeUrl.cmake, modules/YCMEPHelper.cmake
This was causing issues with NFS, and it was not really useful.
Fixes #93
=> IncludeUrl: Remove locks

modules/YCMEPHelper.cmake
=> Fix bootstrap phase with the new ExternalProject

modules/YCMEPHelper.cmake
CC-Issue robotology/robotology-superbuild#175
=> Fix bootstrap again

deprecated/CMakeLists.txt, deprecated/YCMDefaultDirs.cmake, help/manual/ycm-build-system-support.7.rst, help/manual/ycm-modules.7.rst, help/module/YCMDefaultDirs.rst, help/release/0.10.0.rst, modules/CMakeLists.txt
=> Deprecate YCMDefaultDirs module

help/release/0.10.0.rst, modules/InstallBasicPackageFiles.cmake
=> InstallBasicPackageFiles: Deprecate FIRST_TARGET argument

help/release/0.10.0.rst, modules/AddUninstallTarget.cmake
=> AddUninstallTarget: Cleanup and make it FetchContent friendly

deprecated/FindQt3.cmake, find-modules/CMakeLists.txt, help/manual/ycm-modules.7.rst, help/module/FindQt3.rst
=> Deprecate FindQt3 module

help/release/0.10.2.rst, modules/YCMEPHelper.cmake
=> Fix CMAKE_PREFIX_PATH in subprojects

cmake-next/CMakeLists.txt, cmake-next/v3.12.4/Copyright.txt, cmake-next/v3.12.4/FindPython/Support.cmake, help/release/0.10.2.rst
=> Fix FindPython for CMake < 3.7

modules/InstallBasicPackageFiles.cmake
=> Export build directory to user package registry

CMakeLists.txt, modules/InstallBasicPackageFiles.cmake
=> Add `NO_EXPORT` option

3rdparty/eigen3.cmake
Fix https://github.com/robotology/robotology-superbuild/issues/312 .
=> Switch to download Eigen3 files via GitHub

help/manual/ycm-superbuild.7.rst, help/release/0.12.0.rst, modules/FindOrBuildPackage.cmake
Fix https://github.com/robotology/ycm/issues/322
Supersedes https://github.com/robotology/ycm/pull/331
=> FindOrBuildPackage: Add YCM_DISABLE_SYSTEM_PACKAGES option to disable system packages

3rdparty/cmrc.cmake, help/release/0.12.1.rst
Fix https://github.com/robotology/ycm/issues/363 .
=> Fix wrong target in 3rdparty/cmrc.cmake file

3rdparty/uselatex.cmake
Another fix for https://github.com/robotology/ycm/issues/363 .
=> Fix wrong target in 3rdparty/uselatex.cmake file

.github/workflows/python.yml
Should fix https://github.com/robotology/ycm/issues/415. I do not explain to myself either why in all previous releases worked or why this time didn't.
cc @traversaro.
=> Fix deploy workflow to PyPI

CHANGELOG.md, find-modules/FindGLM.cmake
Leftover of https://github.com/robotology/ycm/pull/430 .
=> FindGLM: Fix check for non-existing variable GLM_CONFIG
